# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(400, 300)
        Window.setMinimumSize(QtCore.QSize(400, 300))
        Window.setMaximumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Window.setFont(font)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Window)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 250, 400, 50))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.layout.setContentsMargins(5, 0, 5, 0)
        self.layout.setSpacing(5)
        self.layout.setObjectName("layout")
        self.play_pause_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.play_pause_button.setEnabled(False)
        self.play_pause_button.setObjectName("play_pause_button")
        self.layout.addWidget(self.play_pause_button)
        self.stop_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stop_button.setEnabled(False)
        self.stop_button.setDefault(False)
        self.stop_button.setObjectName("stop_button")
        self.layout.addWidget(self.stop_button)
        self.layout.setStretch(0, 3)
        self.layout.setStretch(1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Window)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 180, 380, 30))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.track_position_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.track_position_label.setFont(font)
        self.track_position_label.setTextFormat(QtCore.Qt.AutoText)
        self.track_position_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.track_position_label.setObjectName("track_position_label")
        self.horizontalLayout.addWidget(self.track_position_label)
        self.track_duration_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.track_duration_label.setFont(font)
        self.track_duration_label.setTextFormat(QtCore.Qt.AutoText)
        self.track_duration_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.track_duration_label.setObjectName("track_duration_label")
        self.horizontalLayout.addWidget(self.track_duration_label)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Window)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(9, 209, 381, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.position_slider = QtWidgets.QSlider(self.horizontalLayoutWidget_3)
        self.position_slider.setEnabled(False)
        self.position_slider.setMaximum(100)
        self.position_slider.setSingleStep(1000)
        self.position_slider.setPageStep(5000)
        self.position_slider.setSliderPosition(0)
        self.position_slider.setOrientation(QtCore.Qt.Horizontal)
        self.position_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.position_slider.setObjectName("position_slider")
        self.horizontalLayout_2.addWidget(self.position_slider)
        self.playback_spinbox = QtWidgets.QDoubleSpinBox(Window)
        self.playback_spinbox.setEnabled(False)
        self.playback_spinbox.setGeometry(QtCore.QRect(320, 10, 70, 30))
        self.playback_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.playback_spinbox.setMinimum(0.5)
        self.playback_spinbox.setMaximum(2.0)
        self.playback_spinbox.setSingleStep(0.1)
        self.playback_spinbox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.playback_spinbox.setProperty("value", 1.0)
        self.playback_spinbox.setObjectName("playback_spinbox")
        self.mute_button = QtWidgets.QPushButton(Window)
        self.mute_button.setEnabled(False)
        self.mute_button.setGeometry(QtCore.QRect(10, 145, 30, 30))
        self.mute_button.setObjectName("mute_button")
        self.volume_slider = QtWidgets.QSlider(Window)
        self.volume_slider.setEnabled(False)
        self.volume_slider.setGeometry(QtCore.QRect(10, 10, 30, 130))
        self.volume_slider.setMaximum(100)
        self.volume_slider.setSliderPosition(100)
        self.volume_slider.setOrientation(QtCore.Qt.Vertical)
        self.volume_slider.setObjectName("volume_slider")
        self.open_button = QtWidgets.QPushButton(Window)
        self.open_button.setGeometry(QtCore.QRect(40, 10, 270, 30))
        self.open_button.setObjectName("open_button")
        self.verticalLayoutWidget = QtWidgets.QWidget(Window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(39, 50, 351, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.title_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.author_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.author_label.setFont(font)
        self.author_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.author_label.setObjectName("author_label")
        self.verticalLayout.addWidget(self.author_label)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Visard"))
        self.play_pause_button.setText(_translate("Window", "Play"))
        self.stop_button.setText(_translate("Window", "Stop"))
        self.track_position_label.setText(_translate("Window", "00:00"))
        self.track_duration_label.setText(_translate("Window", "00:00"))
        self.mute_button.setText(_translate("Window", "🔊"))
        self.open_button.setText(_translate("Window", "Open"))
        self.title_label.setText(_translate("Window", "Title"))
        self.author_label.setText(_translate("Window", "Author"))
